### ISSUE TITLE
Error : java.lang.ClassNotFoundException: io.github.bonigarcia.wdm.WebDriverManager

### ISSUE THREAD

**Issue by bipinmnair89** [bonigarcia/webdrivermanager-examples#13]
Using java version 1.8, Please update on how this issue can be resolved.

Error screenshots
--------------------
<img width="960" alt="WebDriverManagerError" src="https://user-images.githubusercontent.com/54845132/64170749-884d4300-ce6e-11e9-9290-30ad813aea74.png">

<img width="960" alt="WebDriverManager program" src="https://user-images.githubusercontent.com/54845132/64170756-8edbba80-ce6e-11e9-81c0-53eb2ea3b111.png">

Complete error description
-------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/WebDriverManager
	at com.InProgress.WebDriverManagerAPI.initializeMethod(WebDriverManagerAPI.java:17)
	at com.InProgress.WebDriverManagerAPI.main(WebDriverManagerAPI.java:35)
Caused by: java.lang.ClassNotFoundException: io.github.bonigarcia.wdm.WebDriverManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by bipinmnair89** [comment]
Hi,
I was able to solve the issue by removing the below line from the maven dependency as my code was present in the src folder and not in the test folder.

Line which was removed ---->  <scope>test</scope>

**Comment by T-e-j-k-u-m-a-r** [comment]
Can you please share which line was removed @bipinmnair89 ?
Please find the below pom.xml + java sample code for the same. 
--------------------------
Sample Code: 
--------------------------
public static void main(String[] args) throws IOException 
	{
		//setup the chromedriver using WebDriverManager
        WebDriverManager.chromedriver().arch64().setup();
 
        //Create driver object for Chrome
        driver = new ChromeDriver();
 
        //Navigate to a URL
        driver.get("http://toolsqa.com");
        
        //close the browser
        driver.close();
	}
--------------------------
pom.xml content: 
--------------------------
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>ExtentReport</groupId>
	<artifactId>ExtentReport</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<dependencies>
		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>3.1.5</version>
		</dependency>


		
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>


		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.0.0</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.3.2</version>
		</dependency>


	</dependencies>




</project>
----------------------------
Error faced: 

Exception in thread "main" java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/WebDriverManager
	at takeScreenShot.TakeScreenShot_Demo.main(TakeScreenShot_Demo.java:24)
Caused by: java.lang.ClassNotFoundException: io.github.bonigarcia.wdm.WebDriverManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

----------------------------

**Comment by Nivedita01** [comment]
Hope you got the issue resolved. 

You need to comment this line, if your file is in src folder. If your file is in test folder then keep this line as it is.

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>4.0.0</version>
    
</dependency>
