### ISSUE TITLE
IE11: webdriver doesn't execute driver.close()

### ISSUE THREAD

**Issue by hossainmtuhin** [bonigarcia/webdrivermanager-examples#16]
` @Test
    public void launchSite() {
        WebDriverManager.iedriver().setup();
//        WebDriverManager.iedriver().arch64().setup();
        driver = new InternetExplorerDriver();
        driver.manage().window().maximize();
        try {
            driver.get("https://www.wikipedia.org/");
        } catch (TimeoutException e) {
            System.out.println("TimeoutException error is thrown and later handled");
        }
        driver.close();
    }`

For the above test method, the IE11 browser was up and was loaded the page. But the problem is, the browser doesn't get closed and remains open. Later, it throws timeOutError.

**Comment by bonigarcia** [comment]
I think that's an issue about IExplorer. In any case, see [this](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) or [this](https://www.thenews.com.pk/print/703208-internet-explorer-is-dead-as-microsoft-kills-off-25-year-old-browser).
