### ISSUE TITLE
WebDriverManager doesnt run headless for Chrome

### ISSUE THREAD

**Issue by stephenlindo** [bonigarcia/webdrivermanager-examples#17]
Hi,

I have just started using WebDriverManager and think it's great. One issue I have come across is that is doesn't seem to run Chrome headless. 

Please see examples below, one where I'm using WebDriverManager and one where I'm specifying a ChromeDriver location on my pc. When the pc location is specified the test is run in headless mode.  I am using WebDriverManager version 3.7.1.

I'm sure there's something I'm missing, would appreciate any help.

Thanks

**WDM code** 

public class SimpleWDMChrome_Test {
	
	
    private WebDriver driver;

    @BeforeClass
    public static void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    @Before
    public void setupTest() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--disable-gpu");
        driver = new ChromeDriver(options);
    }

    @After
    public void teardown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void test() {
        driver.get("https://www.bbc.co.uk/sport/football");
        String title = driver.getTitle();
        System.out.println(title);
    }

**Chromedriver on PC code**

public class SimpleWDMChrome_Test {
	
	
    private WebDriver driver;

    @BeforeClass
    public static void setupClass() {
        WebDriverManager.chromedriver().setup();
        System.setProperty("webdriver.chrome.driver", "C:\\Drivers\\Chrome\\chromedriver_win32\\chromedriver.exe");
    }

    @Before
    public void setupTest() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--disable-gpu");
        driver = new ChromeDriver(options);
    }

    @After
    public void teardown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void test() {
        driver.get("https://www.bbc.co.uk/sport/football");
        String title = driver.getTitle();
        System.out.println(title);
    }

**Comment by bonigarcia** [comment]
This issue is a bit old, maybe this is already solved. In any case, I have just run this [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ChromeHeadlessTest.java) and it is working nicely.

**Comment by Git-Leon** [comment]
> This issue is a bit old, maybe this is already solved. In any case, I have just run this [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ChromeHeadlessTest.java) and it is working nicely.

This link results in a 404.
