### ISSUE TITLE
Initializing Edge Driver Question

### ISSUE THREAD

**Issue by nylifeinnj** [bonigarcia/webdrivermanager-examples#3]
Hi Mr. Garcia,

I am trying to figure out how to drive the EdgeDriver for my Windows 10 computer.

At this point, I have tried the following (Java) code to initiate Edge:

EdgeDriverManager.getInstance().version("3.14393").setup();

On the basis that EdgeDriver is enacted by the OS Build (14393.1480) and not so much by the Driver version, please advise on what I could be doing wrong.

Thanks!

-Henry C.

**Comment by bonigarcia** [comment]
Ensure which version of Edge are you using, and then force the proper version of the Edge manager (`MicrosoftWebDriver.exe`). More info [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/).
