### ISSUE TITLE
Does not works with M1 out of the box

### ISSUE THREAD

**Issue by nhac-lly** [bonigarcia/webdrivermanager-examples#34]
When I used M1 Mac to run any of the test case, the manager downloaded the intel version of chromedriver instead of m1.

It should check CPU arch automatically and get the correct driver or have an option to download it incase it's failed.

**Comment by bonigarcia** [comment]
This is the examples repository of WebDriverManager. If you have a problem with the tool, please report the issue in the [main repository](https://github.com/bonigarcia/webdrivermanager), explaining all the details of your problem (follow the issue template for that).
