### ISSUE TITLE
java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/ChromeDriverManager

### ISSUE THREAD

**Issue by rajesh99** [bonigarcia/webdrivermanager-examples#6]
I cloned this examples project.
I did mvn test, and got the following errors

Running io.github.bonigarcia.wdm.test.CanvasTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.244 sec <<< FAILURE!
io.github.bonigarcia.wdm.test.CanvasTest  Time elapsed: 0.24 sec  <<< ERROR!
java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/ChromeDriverManager

Running io.github.bonigarcia.wdm.test.ChromeAndFirefoxTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!
io.github.bonigarcia.wdm.test.ChromeAndFirefoxTest  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/ChromeDriverManager

**Comment by barbashaman** [comment]
Same problem here...
