### ISSUE TITLE
WebDriverManager versions and their corresponding browser versions

### ISSUE THREAD

**Issue by clingwithderrick** [bonigarcia/webdrivermanager-examples#7]
We have built a framework in our company and I have suggested to use WebDriverManager. The latest version of WebDriverManager works like a charm with all the browsers that are up-to-date. If we are working on an old version of browser, we need to know which version of the WebDriverManager supports it. In other words, I need the information of which version of WebDriverManager supports the corresponding version of the browsers.

**Comment by bonigarcia** [comment]
WebDriverManager does not match the version of required binaries (e.g. chromedriver or geckodriver) with the corresponding browsers. You should find that info in the versioning provided by the binaries (e.g. [here](http://chromedriver.chromium.org/downloads) or [here](https://github.com/mozilla/geckodriver/releases)).

**Comment by sachinboob** [comment]
Which means the WebDriverManager itself does not have the information/understanding of compatibility mapping between "older" browser and webdriver binary versions.

Is my understanding correct ?

**Comment by bonigarcia** [comment]
@sachinboob As of version 3, WebDriverManager maps internally the version of the browsers and their driver (e.g. Chrome 69 requires chromedriver 2.44). And yes, next time do not use closed issues long time ago for new questions. And use the main repository, i.e. WebDriverManager, this is about examples.
