### ISSUE TITLE
Connection Refuse error for Firefox 52.9.0 (32-bit)

### ISSUE THREAD

**Issue by upendra101087** [bonigarcia/webdrivermanager-examples#8]
Hi Sir ,
I am getting below error while trying to run test in firefox through webdrivermanager .Could you please take a look and reply whats issue . I have 32 bit firefox installed however geckodriver is of 64 bit .Is that the root cause ?
org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'VDF-SYNDEV10', ip: '10.177.225.71', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: FirefoxDriver

**Comment by bonigarcia** [comment]
Not related with WebDriverManager.
