### ISSUE TITLE
Launch browser based on datasheet

### ISSUE THREAD

**Issue by Sureshsekar123** [bonigarcia/webdrivermanager-examples#80]
Hi, is there a way to get browser name from data sheet and launch browser based on that using webdrivermanager

**Comment by bonigarcia** [comment]
This [repo](https://github.com/bonigarcia/selenium-webdriver-java) contains a lot examples of Selenium WebDriver tests using WebDriverManager. For instance, this [one](https://github.com/bonigarcia/selenium-webdriver-java/blob/master/selenium-webdriver-junit5/src/test/java/io/github/bonigarcia/webdriver/jupiter/ch08/cross_browser/CrossBrowserJupiterTest.java) is an example of parameterized test for cross-browser testing.
