### ISSUE TITLE
webdrivermanager is typing very slow in text field on IE browser

### ISSUE THREAD

**Issue by BalurQA** [bonigarcia/webdrivermanager-examples#9]
I am using below dependencies to implement webdrivermanager in my project and it works fine on FF and Chrome. But on it IE sendkeys is typing very slow.

IE version is 11.0.96

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>selenium-jupiter</artifactId>
			<version>2.2.0</version>
		</dependency>

			// DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
			// // this line of code is to resolve protected mode issue
			// capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,
			// true);
			// capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
			// capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
			// capabilities.setCapability("requireWindowFocus", true);
			//
			//
			//// capabilities.setCapability("nativeEvents", false);
			//// capabilities.setCapability("unexpectedAlertBehaviour", "accept");
			//// capabilities.setCapability("ignoreProtectedModeSettings", true);
			//// capabilities.setCapability("disable-popup-blocking", true);
			//// capabilities.setCapability("enablePersistentHover", true);
			//
			// String IEexePath =
			// "src\\\\main\\\\resources\\\\driver\\\\IEDriverServer.exe";
			// System.setProperty("webdriver.ie.driver", IEexePath);
			// driver = new InternetExplorerDriver(capabilities);
			DesiredCapabilities IEcapabilities = DesiredCapabilities.internetExplorer();
			IEcapabilities.setCapability("requireWindowFocus", true);
			WebDriverManager.iedriver().setup();
			driver = new InternetExplorerDriver(IEcapabilities);
			driver.manage().window().maximize();
			driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

**Comment by bonigarcia** [comment]
Not related with WebDriverManager.
